-- MySQL Script generated by MySQL Workbench
-- Fri Jun 28 16:20:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema teste
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `teste` ;

-- -----------------------------------------------------
-- Schema teste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teste` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `teste` ;

-- -----------------------------------------------------
-- Table `tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_categoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_categoria` (
  `nome_categoria` VARCHAR(20) NOT NULL,
  `desc_categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nome_categoria`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_cliente` (
  `id_cliente` INT(4) NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(50) NOT NULL,
  `data_regs` DATE NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `tel_comercial` VARCHAR(11) NOT NULL,
  `tel_celular` VARCHAR(12) NOT NULL,
  `email_cliente` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_dtlh_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_dtlh_pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_dtlh_pedido` (
  `id_pedido` INT(4) NOT NULL,
  `id_produto` INT(4) NOT NULL,
  `qtde_produto_total` INT(3) NOT NULL,
  `pre_total` VARCHAR(10) NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_pedidos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_pedidos` (
  `id_pedido` INT(4) NOT NULL AUTO_INCREMENT,
  `data_pedido` DATE NOT NULL,
  `id_cliente` INT(4) NOT NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_produto` (
  `id_produto` INT(4) NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(50) NOT NULL,
  `desc_produto` VARCHAR(100) NOT NULL,
  `preco_produto` VARCHAR(10) NOT NULL,
  `qtde_produto_estoque` INT(4) NOT NULL,
  `nome_categoria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;